### ISSUE TITLE
Insert as Link option missing?

### ISSUE THREAD

**Issue by ashishbhateja** [argenos/nldates-obsidian#71]
I can no longer find the insert as link option in the plugin settings

![CleanShot 2021-11-29 at 10 04 16@2x](https://user-images.githubusercontent.com/69289857/143797818-b2091c0f-51cd-4e1c-9e40-7e074842fd0e.jpg)

Appreciate any help in troubleshooting this

**Comment by 1Muggle** [comment]
@ashishbhateja  I don't understand what the reason is, I'm having the same problem as you.
My OS is macOS 12.0.1 and Obsidian version is 0.12.19.
Maybe you can try the following (it works for me)

1. Press `Command (probably Ctrl on Windows) + p` to open the command panel
2. Type "Date picker" and press `enter`
3. You should see the following pop-up window, check "Add as link" and click on "Insert Data".
<img width="642" alt="image" src="https://user-images.githubusercontent.com/13177224/144742588-9db2fd6b-12d0-4f36-acef-c0f4ff4c100d.png">
4. At this point you should have a wiki link when you type `@Today` or other phrase in your notes

Good luck!

**Comment by stouf** [comment]
Same thing for me, the `Add as link?` configuration option has disappeared 😞

**Comment by ashishbhateja** [comment]
The Ctrl+P trick works. You may want to try it.

**Comment by stouf** [comment]
> The Ctrl+P trick works. You may want to try it.
> […](#)

`ctrl + p` thing itself works but it doesn’t fix the `@` shortcut afterwards for me 😞

**Comment by ashishbhateja** [comment]
sorry to hear. I hope the developer can fix. this is a very useful plugin to the workflow for many of us

**Comment by jiri** [comment]
It seems that the community plugin store installs version 0.5.0 while clearly being aware of version 0.6.0. The option is present in 0.6.0 -- could this be your issue?

**Comment by stouf** [comment]
> It seems that the community plugin store installs version 0.5.0 while clearly being aware of version 0.6.0. The option is present in 0.6.0 -- could this be your issue?

Ah! Good catch, that's probably it 👍
It's strange though. When I open the page of the plugin in Obsidian, it tells me v0.6.0 is available, I can click on the update button and I get a message telling me the plugin has been successfully updated, but the plugin is stuck on v0.5.0 🤔 I'll have to dig into that.
Any idea where that could come from by any chance?

**Comment by jiri** [comment]
I've got no clue, sorry 😞 I've got no clue how obsidian handles the community plugin support, but if I had to guess, it fetches the releases XML stream from github, looks for the latest one and fetches the files that way, which would suggest the issue _might_ be with obsidian rather than this plugin. Maybe an edge case in `manifest.json` or something?

**Comment by stouf** [comment]
Some more data:

- I have another vault where v0.5.2 was installed; I manually updated it and Obsidian downgraded it to v0.5.0 😮
- I have the same vault synchronized on my iPhone; I updated the plugin and it successfully upgraded it to v0.6.0

That on top of Jiri’s hypothesis [there](https://github.com/argenos/nldates-obsidian/issues/71#issuecomment-989875483), it indeed looks like a bug in Obsidian 🤔
I’ll fill in a bug report on Obsidian’s forum.

**Comment by stouf** [comment]
> I’ll fill in a bug report on Obsidian’s forum.

Just for reference: https://forum.obsidian.md/t/community-plugin-wrong-version-when-installing-and-updating/28339

**Comment by stouf** [comment]
The issue should now be fixed (https://github.com/argenos/nldates-obsidian/pull/74).

@ashishbhateja Shall we close this issue? 🙂

**Comment by ashishbhateja** [comment]
Thank you. Here's what I see after updating:
![image](https://user-images.githubusercontent.com/69289857/145735199-baa97f11-123b-4f13-8441-805db792903a.png)
![image](https://user-images.githubusercontent.com/69289857/145735206-36cbc20e-5d22-42a6-b27c-bf5f2869a2bf.png)

The @ key seems to work ok on desktop now

**Comment by liamcain** [comment]
Closing this since it should be fixed in v0.6.0.
